### ISSUE TITLE
updateAttributes/upsert cause "MongoError: not master"  when running with mongodb replica set

### ISSUE THREAD

**Issue by makersu** [strongloop/loopback-connector-mongodb#111]
UpdateAttributes/upsert will cause MongoError due to update to secondary?

error message:

```
{
  "error": {
    "name": "MongoError",
    "status": 500,
    "message": "not master",
    "note": "from execCommand",
    "ok": 0,
    "errmsg": "not master",
    "stack": "Error\n    at Error.MongoError (/var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:13:17)\n    at Function.MongoError.create (/var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n    at /var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:768:66\n    at Callbacks.emit (/var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)\n    at null.messageHandler (/var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:218:23)\n    at Socket.<anonymous> (/var/lib/strong-pm/.strong-pm/work/666d9c899a7906af6da8589826205806b69c4e9d.1426047850807/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:256:22)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:764:14)\n    at Socket.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:426:10)"
  }
}
```

datasources.json:

```
{
  "db": {
    "url":"mongodb://192.168.4.41,192.168.4.42,192.168.4.43/nucloud?readPreference=secondaryPreferred",
    "connector": "mongodb"
  }
}
```

numessage.js

```
...
Numessage.findOne(
        {
                where: {
                url: data.url
                }
        },
        function(err,numessageInstance) {

                if(numessageInstance && numessageInstance.id){
                        numessageInstance.updateAttributes(data, function(err,obj){
                                if(err){
                                        console.log(err)
                                }
                                cb(err, obj);
                                });
                }
```

**Comment by makersu** [comment]
My solution:
use updateAll instead.
```
Numessage.updateAll({_id:numessageInstance.id},data, function(err,obj){
						if(err){
							console.log(err)
						}
						console.log(obj)
						cb(err, obj);
					});
```

**Comment by wrensburg** [comment]
Ditto here! Any progress yet?

**Comment by vasiliyb** [comment]
Folks, we are seeing this with MongoDB v 2.6.9, nodejs driver 1.4.38.  Any solutions?

**Comment by MrMMorris** [comment]
I am also seeing the `not master` error with `3.0.3`:

```json
{
  "error": {
    "name": "MongoError",
    "status": 500,
    "message": "not master",
    "note": "from execCommand",
    "ok": 0,
    "errmsg": "not master"
  }
}
```

datasources.json:
```json
options: {
      readPreference: 'secondaryPreferred',
      replicaSet: 'replica-1',
    },
```

**Comment by pxwise** [comment]
+1 Any update?

**Comment by dharmendrasdlt** [comment]
@MrMMorris Will this work ? Will this actually use replicaset ?
