### ISSUE TITLE
Issue with MongoDB Connector when using @ within password

### ISSUE THREAD

**Issue by achintverma** [strongloop/loopback-connector-mongodb#188]
When I run sudo npm install loopback-connector-mongodb --save I get following output. 

```
npm WARN package.json investickations@1.0.0 No license field.
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
-
> kerberos@0.0.17 install /var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
loopback-connector-mongodb@1.13.0 node_modules/loopback-connector-mongodb
├── async@1.5.0
├── loopback-connector@2.3.0
├── debug@2.2.0 (ms@0.7.1)
└── mongodb@2.0.48 (es6-promise@2.1.1, readable-stream@1.0.31, kerberos@0.0.17, mongodb-core@1.2.21)
```

Looking at the output it seems that connector is installed. Then I added connection string in DB based on https://docs.strongloop.com/display/public/LB/MySQL+connector

I'm getting following Error when I run application. 

```
/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/url_parser.js:24
    throw new Error('no hostname or hostnames provided in connection string');
    ^

Error: no hostname or hostnames provided in connection string
    at module.exports (/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/url_parser.js:24:11)
    at connect (/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongo_client.js:125:16)
    at Function.MongoClient.connect (/var/www/investickations_web/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongo_client.js:109:3)
    at MongoDB.connect (/var/www/investickations_web/node_modules/loopback-connector-mongodb/lib/mongodb.js:113:25)
    at Object.initializeDataSource [as initialize] (/var/www/investickations_web/node_modules/loopback-connector-mongodb/lib/mongodb.js:70:26)
    at DataSource.setup (/var/www/investickations_web/node_modules/loopback-datasource-juggler/lib/datasource.js:332:17)
    at new DataSource (/var/www/investickations_web/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
    at Registry.createDataSource (/var/www/investickations_web/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/var/www/investickations_web/node_modules/loopback/lib/application.js:415:19)
    at EventEmitter.app.dataSource (/var/www/investickations_web/node_modules/loopback/lib/application.js:222:12)
```

**Comment by achintverma** [comment]
OK, this is not a question now. I figured out the issue. If we pass @ in password string, which was present in my MongoDB password, it fails in URL Parsing since the code in loopback-connector-mongodb/node_modules/mongodb/lib/url_parser.js uses @ character as separator. 

Please fix this issue.

**Comment by dhmlau** [comment]
@achintverma , sorry to take so long to respond.  Do you still have this problem?

**Comment by dhmlau** [comment]
Closing it due to inactivity.  
@achintverma , feel free to reopen if you still encounter this problem.  Thanks.
