### ISSUE TITLE
Latest release fails the tests

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback-connector-mongodb#198]
Hello,

the latest release of the package destroys our tests, that worked with 1.13.0. Here is the error:

```
20) DeliveryTour assign order DEL-12a Optimze Tour load if order capacity would be reached tryMoveWholedayOrder should move wholeday order o2 from t1 to next tour t2 where it just fits exactly [tours_5]:
     Uncaught TypeError: Cannot read property 'type' of undefined
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:577:46
      at Array.map (native)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:576:21
      at Array.forEach (native)
      at MongoDB.buildWhere (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:543:22)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:548:23
      at Array.map (native)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:547:21
      at Array.forEach (native)
      at MongoDB.buildWhere (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:543:22)
      at MongoDB.all (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:675:18)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1511:42
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.find (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1507:10)
      at Function.DeliveryTour.findToursForRegions (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:821:18)
      at Function.DeliveryTour.findTourToAddWholedayOrder (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:612:18)
      at findSuitableTour (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1126:20)
      at iterate (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:146:13)
      at Object.async.eachSeries (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:162:9)
      at Function.DeliveryTour.findWholedayOrderToMove (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1147:11)
      at Function.DeliveryTour.tryMoveWholedayOrder (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1105:18)
      at tryMoveWholedayOrderCall (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/test/delivery/delivery-tour.optimize-order-capacity.spec.js:69:24)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:607:21
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:246:17
      at iterate (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:146:13)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:157:25
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:248:21
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:612:34
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/server/lib/fdTools.js:191:9
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1486:9
      at done (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1470:13
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1466:17
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
      at _each (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
      at Object.async.each (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
      at allCb (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1422:13)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:748:9
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/utils.js:96:12)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:842:16
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
      at setCursorDeadAndNotified (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:554:3)
      at nextFunction (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:731:7)
      at Cursor.next [as _next] (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:772:3)
      at fetchDocs (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:838:10)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:861:7
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
      at nextFunction (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:762:5)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:675:7
      at queryCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:323:5)
      at Callbacks.emit (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
      at null.messageHandler (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
      at Socket.<anonymous> (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:529:20)
      at TCP.onread (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)

  21) DeliveryTour assign order DEL-12a Optimze Tour load if order capacity would be reached tryMoveWholedayOrder should move wholeday order o2 from t1 to tour t3 because this tour is non-empty and preferred over empty tour t2 can take it [tours_6]:
     Uncaught TypeError: Cannot read property 'type' of undefined
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:577:46
      at Array.map (native)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:576:21
      at Array.forEach (native)
      at MongoDB.buildWhere (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:543:22)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:548:23
      at Array.map (native)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:547:21
      at Array.forEach (native)
      at MongoDB.buildWhere (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:543:22)
      at MongoDB.all (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:675:18)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1511:42
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.find (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1507:10)
      at Function.DeliveryTour.findToursForRegions (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:821:18)
      at Function.DeliveryTour.findTourToAddWholedayOrder (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:612:18)
      at findSuitableTour (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1126:20)
      at iterate (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:146:13)
      at Object.async.eachSeries (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:162:9)
      at Function.DeliveryTour.findWholedayOrderToMove (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1147:11)
      at Function.DeliveryTour.tryMoveWholedayOrder (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/common/models/delivery-tour.js:1105:18)
      at tryMoveWholedayOrderCall (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/test/delivery/delivery-tour.optimize-order-capacity.spec.js:69:24)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:607:21
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:246:17
      at iterate (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:146:13)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:157:25
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:248:21
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/async/lib/async.js:612:34
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/server/lib/fdTools.js:191:9
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1486:9
      at done (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1470:13
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at doNotify (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1466:17
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
      at _each (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
      at Object.async.each (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
      at allCb (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-datasource-juggler/lib/dao.js:1422:13)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback-connector-mongodb/lib/mongodb.js:748:9
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/utils.js:96:12)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:842:16
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
      at setCursorDeadAndNotified (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:554:3)
      at nextFunction (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:731:7)
      at Cursor.next [as _next] (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:772:3)
      at fetchDocs (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:838:10)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/lib/cursor.js:861:7
      at handleCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
      at nextFunction (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:762:5)
      at /Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:675:7
      at queryCallback (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:323:5)
      at Callbacks.emit (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
      at null.messageHandler (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
      at Socket.<anonymous> (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:529:20)
      at TCP.onread (/Users/edgarkuskov/Documents/FoodoWorkspace/foodo-api-server/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
```

**Comment by rawrmaan** [comment]
Related to #197

**Comment by Amir-61** [comment]
I just tried `loopback-connector-mongodb` version `1.13.1` and all tests pass.

**Comment by Amir-61** [comment]
I'm closing this ticket since it seems all tests pass with the newer versions. Please feel free to re-open it if you still have the same issue.

Thanks!
