### ISSUE TITLE
We should encodeURIComponent() for username, password and database

### ISSUE THREAD

**Issue by piu130** [strongloop/loopback-connector-mongodb#261]
If you have some special character like @ and others in username, password and database it returns:

```
URIError: Cannot create data source "mongodb": Cannot initialize connector "mongodb": URI malformed
strongloop_1 |     at decodeURIComponent (native)
strongloop_1 |     at Url.parse (url.js:261:19)
strongloop_1 |     at Object.urlParse [as parse] (url.js:67:5)
strongloop_1 |     at module.exports (/code/node_modules/mongodb/lib/url_parser.js:17:23)
strongloop_1 |     at connect (/code/node_modules/mongodb/lib/mongo_client.js:176:16)
strongloop_1 |     at Function.MongoClient.connect (/code/node_modules/mongodb/lib/mongo_client.js:109:3)
strongloop_1 |     at MongoDB.connect (/code/node_modules/loopback-connector-mongodb/lib/mongodb.js:141:25)
strongloop_1 |     at Object.initializeDataSource [as initialize] (/code/node_modules/loopback-connector-mongodb/lib/mongodb.js:84:28)
strongloop_1 |     at DataSource.setup (/code/node_modules/loopback-datasource-juggler/lib/datasource.js:338:19)
strongloop_1 |     at new DataSource (/code/node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
```

We should encode the components before using them.
Should be somewhere in `mongodb.js` in the function `generateMongoDBURL(options)`.

**Comment by maricn** [comment]
+ vote
