### ISSUE TITLE
MongoError: no primary found in replicaset

### ISSUE THREAD

**Issue by codymwalker** [strongloop/loopback-connector-mongodb#354]
- [X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

In using any version of `loopback-connector-mongodb` that pulls in a `mongodb` version of `2.2.x` as a dependency fails to connect when we are targeting a replica set using TLS where the replica set. The drivers are trying to contact the replicaset members on using their IP addresses 

### Expected result

Successful connection

### Actual result (if bug)

```
MongoError: no primary found in replicaset
    at /app/node_modules/mongodb-core/lib/topologies/replset.js:524:28
    at Server.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/replset.js:303:24)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Object.cb (/app/node_modules/mongodb-core/lib/topologies/server.js:260:55)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:243:32)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at TLSSocket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:199:12)
    at TLSSocket.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at Socket._handle.close (net.js:498:12)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
```

### Additional information (Node.js version, LoopBack version, etc)

MongoDB Version: 3.2.8
Node Version: 6.9.1
Loopback Version: 2.18.0

Does not work
```
├─┬ loopback-connector-mongodb@1.18.1
│ ├── async@1.5.2
│ ├─┬ loopback-connector@2.7.7
│ │ ├── async@1.5.2
│ │ ├── bluebird@3.4.7
│ │ └─┬ msgpack5@3.4.1
│ │   └── bl@1.2.0
│ └─┬ mongodb@2.2.24
│   ├── es6-promise@3.2.1
│   ├─┬ mongodb-core@2.1.8
│   │ ├── bson@1.0.4
│   │ └─┬ require_optional@1.0.0
│   │   └── semver@5.3.0
│   └── readable-stream@2.1.5
```

Does work:
```
├─┬ loopback-connector-mongodb@1.17.0
│ ├── async@1.5.2
│ ├─┬ loopback-connector@2.7.7
│ │ ├── async@1.5.2
│ │ ├── bluebird@3.4.7
│ │ └─┬ msgpack5@3.4.1
│ │   └── bl@1.2.0
│ └─┬ mongodb@2.1.21
│   ├── es6-promise@3.0.2
│   ├─┬ mongodb-core@1.3.21
│   │ ├── bson@0.4.23
│   │ └─┬ require_optional@1.0.0
│   │   └── semver@5.3.0
│   └─┬ readable-stream@1.0.31
│     └── isarray@0.0.1
```

**Comment by hrhyt** [comment]
I also experienced the same problem.

Please read the following documents.
https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#clients-use-the-hostnames-listed-in-the-replica-set-config-not-the-seed-list

The behavior of mongodb 2.1.x and 2.0.x seems to be a bug.
https://jira.mongodb.org/browse/NODE-753

**Comment by dhmlau** [comment]
@codymwalker, Based on the comments from @raymondfeng in #319 
>Based on our investigation, the issue is caused by mongodb@2.x. See:
> - Automattic/mongoose#4596
> - https://jira.mongodb.org/browse/NODE-816?jql=text%20~%20%22MongoError%3A%20no%20primary%20found%20in%20replicaset%22
>Before we have a fix from the driver, maybe we should set the dependency to mongodb@~2.1.21.
