### ISSUE TITLE
UpsertWithWhere crashes with model strict "filter" and instance already persisted

### ISSUE THREAD

**Issue by Elrendio** [strongloop/loopback-connector-mongodb#445]
# Description/Steps to reproduce

 - [x] Clone the [forked repo](https://github.com/Elrendio/loopback-sandbox)
 - [x] Go on branch for the bug:
```git checkout 445-UpsertWithWhereCrashesWithModelStrictFilterAndInstanceAlreadyPersisted```
 - [x] run ```npm install```
 - [x] Make sure you have a mongodb instance opened on port 27017
 - [x] run ```node server/server.js```
 - [x] Look at logs.
# Link to reproduction sandbox
 [Sandbox](https://github.com/Elrendio/loopback-sandbox)

# Expected result
  Instance should be updated without any warnings or errors.

# Actual Results
  Console outputs error:
```
(node:39828) UnhandledPromiseRejectionWarning: ValidationError: The `MyPersistedModel` instance is not valid. Details: `myKey2` is not defined in the model (value: undefined).
    at /Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/dao.js:3273:16
    at MyPersistedModel.<anonymous> (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/validations.js:578:11)
    at MyPersistedModel.next (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
    at MyPersistedModel.<anonymous> (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/validations.js:575:23)
    at MyPersistedModel.trigger (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
    at MyPersistedModel.Validatable.isValid (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/validations.js:541:8)
    at validateAndSave (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/dao.js:3271:14)
    at applyStrictCheck (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/dao.js:100:3)
    at /Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/dao.js:3246:7
    at doNotify (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
```

# Additional information
 - Latest commit adds the code for the bug.
 - Cannot reproduce the bug when database used is memory.
 - Didn't try with other databases
 - npm: 4.6.1
 - node -e 'console.log(process.platform, process.arch, process.versions.node)':
```
darwin x64 9.8.0
```
 - npm ls --prod --depth 0 | grep loopback:
```
loopback-sandbox@1.0.0 /Users/elrendio/Workspace/BugReports/LoopBack/PersistedModelUpsertWithWhereCrashesWhenStrictFilter
├── loopback@3.21.0
├── loopback-boot@3.1.0
├── loopback-component-explorer@6.1.0
├── loopback-connector-mongodb@3.4.4
```

**Comment by jannyHou** [comment]
should be fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1423
