### ISSUE TITLE
version 3.9.2 has changed behavior with model properties of type "object"

### ISSUE THREAD

**Issue by tflowcamdev** [strongloop/loopback-connector-mongodb#486]
# Description/Steps to reproduce

We have models with properties of type "object", for example "objprop" below:

```
{
    "name": "TestModel",
    "plural": "testmodels",
    "base": "PersistedModel",
    "idInjection": true,
    "replaceOnPUT": false,
    "options": {
      "validateUpsert": true
    },
    "properties": {
      "name": {
        "type": "string",
        "required": true
      },
      "objprop": {
        "type": "object",
        "required": false
      }
    },
    "validations": [],
    "relations": {},
    "methods": {}
}
```

Now previously we could insert strings or arrays or objects into this property (v3.9.1 is still working), but with v 3.9.2 of the loopback-mongodb-connector, suddenly inserting a string values throws an exception.

Perhaps this is not a best practice, but we do have some models that use type object where we insert strings, or arrays or objects and this has previously worked.

It looks like array values still don't cause an issue, just string values.

# Expected result

Sample code with the model above:

```
   var data = {
        name: 'abcd',
        objprop: '',
      };
      var createResp = await TestModel.create(data);
```

This will produce the error with version 3.9.2:

```
     TypeError: Cannot assign to read only property 'length' of object '[object String]'
      at node_modules/loopback-connector-mongodb/lib/mongodb.js:2010:15
      at Array.forEach (<anonymous>)
      at convertDecimalProps (node_modules/loopback-connector-mongodb/lib/mongodb.js:2009:13)
      at node_modules/loopback-connector-mongodb/lib/mongodb.js:2010:17
      at Array.forEach (<anonymous>)
      at convertDecimalProps (node_modules/loopback-connector-mongodb/lib/mongodb.js:2009:13)
      at MongoDB.toDatabase (node_modules/loopback-connector-mongodb/lib/mongodb.js:426:3)
      at MongoDB.create (node_modules/loopback-connector-mongodb/lib/mongodb.js:561:15)
      at invokeConnectorMethod (node_modules/loopback-datasource-juggler/lib/dao.js:171:21)
      at node_modules/loopback-datasource-juggler/lib/dao.js:460:11
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at TestModel.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:457:15)
      at TestModel.trigger (node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
      at TestModel.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:392:11)
      at TestModel.trigger (node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
      at create (node_modules/loopback-datasource-juggler/lib/dao.js:391:9)
      at node_modules/loopback-datasource-juggler/lib/dao.js:383:9
      at TestModel.<anonymous> (node_modules/loopback-datasource-juggler/lib/validations.js:578:11)
      at TestModel.next (node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
      at TestModel.<anonymous> (node_modules/loopback-datasource-juggler/lib/validations.js:575:23)
      at TestModel.trigger (node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
      at TestModel.Validatable.isValid (node_modules/loopback-datasource-juggler/lib/validations.js:541:8)
      at node_modules/loopback-datasource-juggler/lib/dao.js:381:9
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at Function.DataAccessObject.create (node_modules/loopback-datasource-juggler/lib/dao.js:365:9)
```

# Additional information

  node -e 'console.log(process.platform, process.arch, process.versions.node)'

darwin x64 8.11.4  

  npm ls --prod --depth 0 | grep loopback

├── loopback@3.23.2

**Comment by jannyHou** [comment]
Hi @tflowcamdev 3.9.2 contains a feature PR that detects the nested property's type in an object property, I think that's why you see a behavior change. 

According to your model definition, 
```js
"objprop": {
        "type": "object",
        "required": false
      }
```
restricts the type of data to be an object, so theoretically you could not provide a string data(or array data)...

**Comment by tflowcamdev** [comment]
Thanks for the quick reply @jannyHou  - because of the loose nature of these things, we're already using some properties where we could have a string, array or object - is there a type we can put on the property to allow this?  I would prefer this to having to remove the property from the model json entirely.
