### ISSUE TITLE
referencesMany relation causes "is not an ObjectId string" error.

### ISSUE THREAD

**Issue by Hulcsa** [strongloop/loopback-connector-mongodb#537]
Hello,

I have a referencesMany relation in one of my models, and since v5.0.0 I cannot create a new object from this model, but it works perfectly fine with v4.2.0. The relation is this:

"foods": {
  "type": "referencesMany",
  "model": "Food",
  "foreignKey": "foodIds",
  "options": {
    "validate": true,
    "forceId": false
  }
}

When i delete this relation, i can create an object from this model without an error, but now i get the following error:

Error:  is not an ObjectID string
at coerceToObjectId (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:1915:13)
at coercePropertyValue (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:2108:17)
at visitAllProperties (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:2072:7)
at MongoDB.toDatabase (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:424:5)
at MongoDB.create (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:576:15)
at invokeConnectorMethod (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\dao.js:172:21)
at C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\dao.js:445:11
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at Function.ObserverMixin._notifyBaseObservers (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:178:5)
at Function.ObserverMixin.notifyObserversOf (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
at Function.ObserverMixin._notifyBaseObservers (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
at Function.ObserverMixin.notifyObserversOf (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)

**Comment by mrbatista** [comment]
Confirm same problem. [See sandbox](https://github.com/mrbatista/loopback-sandbox/tree/error-relation-objectid).
To replicate (require a mongodb database listen on port 27017):
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
 "id": "5d59804788cb43842ec72f36", \ 
 "name": "customer1"}' 'http://localhost:3000/api/Customers'`

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"price": 1}' 'http://localhost:3000/api/Customers/5d59804788cb43842ec72f36/orders'`

`Unhandled error for request POST /Customers/5d59804788cb43842ec72f36/orders: Error: 5d59804788cb43842ec72f36 is not an ObjectID string

**Comment by imran-solanki** [comment]
i am also getting same issue.  and i have fix my issue. loopback-connector-mongodb 5.0.0 is not support referencesMany relation i have changed update version 4.2.0  it's working prefect

**Comment by Limpidius-Fred** [comment]
mongodb.js#1939
replace:
```
  } else if (value instanceof ObjectID) {
```
with:
```
  } else if (value instanceof mongodb.ObjectID) {
```

**Comment by mrbatista** [comment]
@Hulcsa form me with latest version (5.2.1) the problem is resolved.
Please verify and report feedback.

**Comment by mikeevstropov** [comment]
"loopback-connector-mongodb": "5.2.1"

```
"relations": {
  "categories": {
    "type": "referencesMany",
    "model": "Categories",
    "foreignKey": "categoryIds",
    "options": {
      "validate": true,
      "forceId": false
    }
  }
}
```

POST `http://localhost:3000/api/News` with following body

```
{
  categoryIds: []
}
```

will fail with

```
Error:  is not an ObjectID string
    at coerceToObjectId (/node_modules/loopback-connector-mongodb/lib/mongodb.js:1950:13)
    at coercePropertyValue (/node_modules/loopback-connector-mongodb/lib/mongodb.js:2143:17)
    at visitAllProperties (/node_modules/loopback-connector-mongodb/lib/mongodb.js:2107:7)
    at MongoDB.toDatabase (/node_modules/loopback-connector-mongodb/lib/mongodb.js:437:5)
    at MongoDB.create (/node_modules/loopback-connector-mongodb/lib/mongodb.js:589:15)
    at invokeConnectorMethod (/node_modules/loopback-datasource-juggler/lib/dao.js:172:21)
    at /node_modules/loopback-datasource-juggler/lib/dao.js:447:11
```

**Comment by redakzter01** [comment]
Hello everybody, this is my hack to mongodb.js and "loopback-connector-mongodb": "5.2.1"

`/**
 * Check whether the property is an ObjectID (or Array thereof)
 *
 */
function isObjectIDProperty(modelCtor, propDef, value, options) {
  if (!propDef) return false;

  if (typeof value === 'string' && value.match(ObjectIdValueRegex)) {
    if (isStoredAsObjectID(propDef)) return true;
    else return !isStrictObjectIDCoercionEnabled(modelCtor, options);
  } else if (value instanceof mongodb.ObjectID) {
    return true;
  } else if(Array.isArray(value)) {
    return value.every( item => mongodb.ObjectId.isValid(item) )
  } else {
    return false;
  }
}`


Just added a condition to validate when value is an array of ObjectId....
