### ISSUE TITLE
Module ./connectors/mongodb not found, will try another candidate.

### ISSUE THREAD

**Issue by josephlaw** [strongloop/loopback-connector-mongodb#539]
# Description/Steps to reproduce
Got below error after upgrade loopback-connector-mongodb from 3.0.1 to 3.1.0
Remarks: I tried to use loopback-datasource-juggler@2.59.2 or up still have the same error. I haven't start/use mongodb access control (that mean no need user/password)

 loopback:datasource Module ./connectors/mongodb not found, will try another candidate. +0ms
  loopback:datasource Cannot load connector loopback-connector-mongodb: SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/joseph/projects/food/server/node_modules/loopback-connector-mongodb/node_modules/loopback-connector/index.js:7:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/joseph/projects/food/server/node_modules/loopback-connector-mongodb/lib/mongodb.js:13:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/joseph/projects/food/server/node_modules/loopback-connector-mongodb/index.js:9:18) +103ms

loopback-connector-mongodb 3.0.1  loopback-datasource-juggler@2.59.2
loopback-connector-mongodb 3.1.0 fail

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@hacksparrow, have you seen this problem? 
@josephlaw, would you consider updating `loopback-datasource-juggler` to 3.x or 4.x? It's because 2.x is already end of life.

**Comment by hacksparrow** [comment]
@josephlaw to help us diagnose the issue, please share a bare minimum app which reproduces the issue you are encountering.

Unless there is a restriction, we recommend you upgrade to `loopback-datasource-juggler` `3.x` or `4.x`.

**Comment by josephlaw** [comment]
Already tested 3.x and 4.x, also got the same problem, thanks

**Comment by hacksparrow** [comment]
@josephlaw please share a bare minimum app which reproduces the issue, we will be able to help you fix it.

**Comment by josephlaw** [comment]
@hacksparrow https://github.com/josephlaw/loopback-test.git

**Comment by josephlaw** [comment]
@hacksparrow https://github.com/josephlaw/lp_test.git

**Comment by josephlaw** [comment]
@hacksparrow @dhmlau I tried to upgrade my nodejs version from v4.8.3 to v6.10.x, and no such database connection problem, thanks .
