### ISSUE TITLE
DeprecationWarning: option useUnifiedTopology to MongoClient.connect

### ISSUE THREAD

**Issue by herbertscruz** [strongloop/loopback-connector-mongodb#540]
(node:9048) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.
    at parseFn (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/operations/connect.js:312:5)
    at parseConnectionString (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/core/uri_parser.js:628:3)
    at connect (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/operations/connect.js:266:3)
    at ConnectOperation.execute (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/operations/connect.js:191:5)
    at executeOperation (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/operations/execute_operation.js:94:26)
    at MongoClient.connect (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/mongodb/lib/mongo_client.js:216:10)
    at MongoDB.connect (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-connector-mongodb/lib/mongodb.js:298:62)
    at Object.initializeDataSource [as initialize] (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-connector-mongodb/lib/mongodb.js:115:28)
    at DataSource.setup (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-datasource-juggler/lib/datasource.js:502:19)
    at new DataSource (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
    at Registry.createDataSource (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback/lib/registry.js:364:12)
    at dataSourcesFromConfig (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback/lib/application.js:570:19)
    at Function.app.dataSource (/home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback/lib/application.js:269:14)
    at /home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-boot/lib/executor.js:191:9
    at /home/herberts/Projects/workspace/aegon/platform-api/node_modules/loopback-boot/lib/executor.js:282:5
    at Array.forEach (<anonymous>)

**Comment by heshamelmasry77** [comment]
any fix for this issue ! ?

**Comment by herbertscruz** [comment]
I'm waiting to approve.

https://github.com/strongloop/loopback-connector-mongodb/pull/541

**Comment by siarheidudko** [comment]
keep in mind that in the case {useUnifiedTopology: true}  of connection with mongo never restores
https://jira.mongodb.org/browse/NODE-2147

**Comment by Tamilselvanret** [comment]
Problem Fixed... Use this @herbertscruz 
Mongodb deprecated **current server and engine monitoring** method , So you need to use **new server and engine monitoring** method.. So use 

>  { useUnifiedTopology:true }
`mongoose.connect(process.env.test_db, { useUnifiedTopology: true, useNewUrlParser: true, useCreateIndex: true  });`

Ref: https://stackoverflow.com/a/57900760/11873380

**Comment by flow08** [comment]
This helps me. Go to "\node_modules\loopback-connector-mongodb\lib\mongodb.js" file in your project root. Put "validOptions['useUnifiedTopology'] = true;" between 296 and 297 lines.

**Comment by emersomcarvalho** [comment]
mongoose.connect('mongodb://localhost:27017/<name of base>',
{useNewUrlParser: true, useUnifiedTopology: true}); // for version  "5.7.1" - Resolved  :)

**Comment by carlos-peru** [comment]
Is this going to get merge into v3 as well?

**Comment by raymondfeng** [comment]
@carlos-peru Can you cherry-pick the commits and submit a patch for 3.x branch?

**Comment by carlos-peru** [comment]
@raymondfeng done: #548

**Comment by adhikmewada** [comment]
Thanks

**Comment by Thetchina13** [comment]
Thanks a lot  :)

**Comment by rporta** [comment]
thank you very much for working on this error add this line in my package.json. I can now use useUnifiedTopology. Seriously thank you very much, I was about to upload a fix to my private repository. I save myself a lot of headaches


line: "loopback-connector-mongodb": "git + https: //github.com/strongloop/loopback-connector-mongodb.git#v5.1.0"
