### ISSUE TITLE
 Cannot read property value of null

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback-connector-mongodb#81]
[On line 382 of mongodb.js](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L382), `result` could be null if err is returned in callback from mongodb.

```javascript
this.collection(model).findAndModify({
    _id: oid
  }, [
    ['_id', 'asc']
  ], data, {upsert: true, new: true}, function (err, result) {
    if (self.debug) {
      debug('updateOrCreate.callback', model, id, err, result);
    }
    var object = result.value;
    if (!err && !object) {
      // No result
      err = 'No ' + model + ' found for id ' + id;
    }
    self.setIdValue(model, object, id);
    object && idName !== '_id' && delete object._id;
    callback && callback(err, object);
  });
```

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-connector-mongodb/commit/26e99a8b5e783672c3455b5633e63cc83d78f0e3

**Comment by miu-zsolt** [comment]
I have a similar issue. Could you please help me?

```
TypeError: Cannot read property 'value' of null
    at /opt/app/backend/node_modules/loopback-connector-mongodb/lib/mongodb.js:669:24
    at handleCallback (/opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:93:12)
    at /opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/collection.js:1395:22
    at handleCallback (/opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:93:12)
    at /opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/db.js:245:20
    at /opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:443:5
    at /opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:742:46
    at /opt/app/backend/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17
    at b (domain.js:183:18)
    at Callbacks.emit (/opt/app/backend/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
```
