### ISSUE TITLE
ECONNREFUSED when deploy on heroku

### ISSUE THREAD

**Issue by assiomatica** [strongloop/loopback-connector-mongodb#96]
Hi,

I have a strongloop app working pefectly on local even connecting to a remote mongo instance
But when I deploy on heroku or modulus.io I get ECONNREFUSED error doesnt matter where is the mongo instance,

Somebody have experience on StrongLoop on Heroku or Modulus.io?

Thank in advance!

Antonio

**Comment by raymondfeng** [comment]
Do you use the mongodb hosted by heroku?

**Comment by assiomatica** [comment]
Yes I am using mongolab add-on


Antonio Casula

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/

**Comment by n8stowell82** [comment]
Have there been any updates on this?  I am having the same issue while trying to connect to a Postgres DB on heroku.  With the loopback app running locally I can successfully connect and use the heroku hosted db, however, as soon as I deploy my loopback app I get the the 'ECONNREFUSED' error.  Below is a log dump from the app running on heroku:
``` 
Web server listening at: http://0.0.0.0:44716/
2015-05-04T05:19:57.974818+00:00 app[web.1]: Error: connect ECONNREFUSED
2015-05-04T05:19:57.974822+00:00 app[web.1]:     at Object.afterConnect [as oncomplete] (net.js:896:19)
2015-05-04T05:19:57.969927+00:00 app[web.1]: Browse your REST API at http://0.0.0.0:44716/explorer
2015-05-04T05:19:57.974177+00:00 app[web.1]:   syscall: 'connect' } 
2015-05-04T05:19:57.974169+00:00 app[web.1]: Connection fails:  { [Error: connect ECONNREFUSED]
2015-05-04T05:19:57.974178+00:00 app[web.1]: It will be retried for the next request.
2015-05-04T05:19:57.974608+00:00 app[web.1]: 
2015-05-04T05:19:57.974173+00:00 app[web.1]:   code: 'ECONNREFUSED',
2015-05-04T05:19:57.974175+00:00 app[web.1]:   errno: 'ECONNREFUSED',
2015-05-04T05:19:58.746570+00:00 heroku[web.1]: State changed from starting to crashed
2015-05-04T05:19:58.735569+00:00 heroku[web.1]: Process exited with status 8

**Comment by afaucogney** [comment]
Which mongodb address did you set on the datasource json file ?

**Comment by assiomatica** [comment]
Hi ,
I set the address showed in the mongodb service on heroku.
but this is an old issue , was solved changing my node.js code and now I
cannot rember how.

Sorry

Antonio Casula

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/

**Comment by seanbrookes** [comment]
I just ran into this issue while deploying a loopback app to heroku.

``` 2015-07-22T07:06:11.441996+00:00 heroku[web.1]: Starting process with command `node server/server`
2015-07-22T07:06:12.666076+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-22T07:06:12.666099+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-22T07:06:14.717357+00:00 app[web.1]: It will be retried for the next request.
2015-07-22T07:06:14.718155+00:00 app[web.1]: 
2015-07-22T07:06:14.718158+00:00 app[web.1]: /app/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/server.js:228
2015-07-22T07:06:14.688265+00:00 app[web.1]: Browse your REST API at http://0.0.0.0:16494/explorer
2015-07-22T07:06:14.717352+00:00 app[web.1]: Connection fails:  { [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' } 
2015-07-22T07:06:14.718166+00:00 app[web.1]: Error: connect ECONNREFUSED
2015-07-22T07:06:14.718160+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-07-22T07:06:14.718170+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
2015-07-22T07:06:14.718161+00:00 app[web.1]:                                             ^
2015-07-22T07:06:14.718168+00:00 app[web.1]:     at exports._errnoException (util.js:746:11)
2015-07-22T07:06:14.689640+00:00 app[web.1]: Web server listening at: http://0.0.0.0:16494/
2015-07-22T07:06:15.627177+00:00 heroku[web.1]: State changed from starting to crashed
 ```

I was able to resolve it by reverting my loopback-connector-mongodb version to one from a known working project

The version I am using that works is 1.8.0
The offending version was 1.11.3

**Comment by seanbrookes** [comment]
update:  
after verifying with a working version on heroku, I deleted the version 1.8 loopback-connector-mongodb folder from node_modules and re-installed the latest: 
``` npm install loopback-connector-mongodb --save ```

re-deployed to heroku and the problem seems to have gone away

**Comment by riemers** [comment]
For people coming with the same issue, in my case i had an entry in there that was faulty. My assumption was that it would only 'load' the configs of my model-config.json. So i had mongo in model-config but still had a postgre in datasources.json (which i didn't use anymore, but was bad)

**Comment by dhmlau** [comment]
Closing due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue.
